server:
  port: 8080

spring:
  application:
    name: gateway-service

security:
  jwt:
    secret: ChangeThisSecretToAtLeast32Bytes!!

gateway:
  nacos:
    route-publish:
      enabled: true
      data-id: gateway-routes.yaml
      group: DEFAULT_GROUP
      type: yaml
      classpath-file: gateway-routes.yaml
